### ISSUE TITLE
Daily Timestamp Testing

### ISSUE THREAD

**Issue by sreejithkaimal** [hashgraph/hedera-wallet-android#47]
<a href="https://github.com/DSMatusevich"><img src="https://avatars0.githubusercontent.com/u/42348838?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [DSMatusevich](https://github.com/DSMatusevich)**
_Monday Feb 11, 2019 at 15:20 GMT_
_Originally opened as https://github.com/swirlds/clients-hedera/issues/238_

----

Daily Timestamp Testing user story: 

All issues related to testing the website will be linked here

- [ ] Extension Detection (Issue #244)
- [ ] Payment Detection (Issue #245)
- [ ] Test tags (Issue #246)

All tests must be performed for different operating systems: Mac OS, Windows (10, 7), Linux, and Chromium.
