### ISSUE TITLE
Chrome Extension Testing

### ISSUE THREAD

**Issue by sreejithkaimal** [hashgraph/hedera-wallet-android#48]
<a href="https://github.com/DSMatusevich"><img src="https://avatars0.githubusercontent.com/u/42348838?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [DSMatusevich](https://github.com/DSMatusevich)**
_Monday Feb 11, 2019 at 15:21 GMT_
_Originally opened as https://github.com/swirlds/clients-hedera/issues/239_

----

Main Chrome Extension User Story:

All issues related to automated testing of the chrome extension will be linked here

- [ ]  Protobuf changes (testing changes in protobuf on the extension side)
- [ ] API Changes
- [ ] Signature Structure due to Complex Keys (Issue #247)
- [ ] Errors due to Throttling (Issue #248)
- [ ] Recent transactions history issues (Issue #224)
- [ ] Security testing (Issue #203, #205 for instance)

All tests must be performed for different operating systems: Mac OS, Windows (10, 7), Linux, and Chromium.
